"""add fleet_no to vehicles

Revision ID: 641c9ee91cf7
Revises: 94d289815c90
Create Date: 2026-05-25 22:28:57.235778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641c9ee91cf7'
down_revision: Union[str, None] = '94d289815c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('fleet_no', sa.String(), nullable=True))
    op.create_index(op.f('ix_vehicles_fleet_no'), 'vehicles', ['fleet_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_fleet_no'), table_name='vehicles')
    op.drop_column('vehicles', 'fleet_no')
    # ### end Alembic commands ###